services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      REDIS_URL: $REDIS_URL
      REDIS_PASSWORD: $REDIS_PASSWORD

  redis:
    image: redis:alpine
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]

