name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: europe-west1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      
      - name: Configure Docker with gcloud
        run: gcloud auth configure-docker $GCP_REGION-docker.pkg.dev

      - name: Build and push Docker Image
        run: |
          docker build --no-cache -t $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/blogging-repo/blog .
          docker push $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/blogging-repo/blog

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy blogging-repo \
            --image $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/blogging-repo/blog \
            --platform managed \
            --region $GCP_REGION \
            --allow-unauthenticated \
            --timeout=300s \
            --port 8080
