name: Sinatra API Tests

on: [push, pull_request] # Runs tests on every push & PR

jobs:
  test:
    runs-on: ubuntu-latest # Debian-based runner, no Windows pain
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: runner
          POSTGRES_DB: blogging
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U runner -d blogging"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true # Automatically install dependencies

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Set up database
        run: |
          psql -h localhost -U runner -d blogging -c "CREATE TABLE IF NOT EXISTS posts (
            id SERIAL PRIMARY KEY,
            title TEXT NOT NULL,
            content TEXT NOT NULL,
            author TEXT NOT NULL,
            thumbnail TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          );"

          psql -h localhost -U runner -d blogging -c "CREATE TABLE IF NOT EXISTS users (
            id SERIAL PRIMARY KEY,
            username TEXT NOT NULL UNIQUE,
            password TEXT NOT NULL
          );"

      - name: Run tests
        run: rspec
        env:
          DATABASE_URL: "postgres://runner:runner@localhost:5432/blogging"
